// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1nt6rUKcTQNTEoPdlDxCSUMStaSjfMHg',
    appId: '1:140266050215:web:188b464f42615dcd0a4182',
    messagingSenderId: '140266050215',
    projectId: 'lab-test-6adee',
    authDomain: 'lab-test-6adee.firebaseapp.com',
    storageBucket: 'lab-test-6adee.firebasestorage.app',
    measurementId: 'G-24WF7K2G83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmV4t7MfDVKloqmAiL0KktX667anMwJ1A',
    appId: '1:140266050215:android:d19a0da63d50ab9c0a4182',
    messagingSenderId: '140266050215',
    projectId: 'lab-test-6adee',
    storageBucket: 'lab-test-6adee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcWhglWmfr4akF9U-FfzvnxLt2tWsYLg',
    appId: '1:140266050215:ios:888de5238497c1010a4182',
    messagingSenderId: '140266050215',
    projectId: 'lab-test-6adee',
    storageBucket: 'lab-test-6adee.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxcWhglWmfr4akF9U-FfzvnxLt2tWsYLg',
    appId: '1:140266050215:ios:888de5238497c1010a4182',
    messagingSenderId: '140266050215',
    projectId: 'lab-test-6adee',
    storageBucket: 'lab-test-6adee.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1nt6rUKcTQNTEoPdlDxCSUMStaSjfMHg',
    appId: '1:140266050215:web:9f00f483dad8504d0a4182',
    messagingSenderId: '140266050215',
    projectId: 'lab-test-6adee',
    authDomain: 'lab-test-6adee.firebaseapp.com',
    storageBucket: 'lab-test-6adee.firebasestorage.app',
    measurementId: 'G-ZFBM3CLH1X',
  );
}
